/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author louienicholaslee International School Manila 13-inch
 * MacBook Pro, NetBeans. Purpose: To help facilitate learning of new vocabulary in
 * foreign languages
 * 
 * Allows user to change languages
 */
public class ChangeLanguagesForm extends javax.swing.JDialog {

    /**
     * Creates new form ChangeLanguages
     */
    
    //Stores the language that will be worked on
    private String language;
    
    //Accesssor method
    public String getLanguage(){
        return language;
    }
    
    //Constructor
    public ChangeLanguagesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Chinese = new javax.swing.JButton();
        French = new javax.swing.JButton();
        Spanish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Chinese.setText("Chinese");
        Chinese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChineseActionPerformed(evt);
            }
        });

        French.setText("French");
        French.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchActionPerformed(evt);
            }
        });

        Spanish.setText("Spanish");
        Spanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpanishActionPerformed(evt);
            }
        });

        jLabel1.setText("Which language do you want to study?");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(Chinese)
                        .add(18, 18, 18)
                        .add(French)
                        .add(18, 18, 18)
                        .add(Spanish))
                    .add(layout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Chinese)
                    .add(French)
                    .add(Spanish))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Changes the language to chinese before closing the form
    private void ChineseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChineseActionPerformed
        language = "Chinese";
        this.dispose();
    }//GEN-LAST:event_ChineseActionPerformed

    //Changes the language to french before closing the form
    private void FrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchActionPerformed
        language = "French";
        this.dispose();
        
    }//GEN-LAST:event_FrenchActionPerformed

    //Changes the language to spanish before closing the form
    private void SpanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpanishActionPerformed
        language = "Spanish";
        this.dispose();
    }//GEN-LAST:event_SpanishActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chinese;
    private javax.swing.JButton French;
    private javax.swing.JButton Spanish;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
