
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author louienicholaslee International School Manila 13-inch
 * MacBook Pro, NetBeans. Purpose: To help facilitate learning of new vocabulary in
 * foreign languages
 * 
 * allows user to edit/add vocabulary sets
 */
public class EditSetForm extends javax.swing.JDialog {
    //Stores the words in the set
    private Word[] wordArray = new Word[AppLogic.MAX_NUM_WORDS];
    //Stores then number of words in the set
    private int numWords = 0;
    private String title = null;
    private boolean phoneticLanguage;

    
    //Constructor form for editing a preexisting vocabulary set 
    public EditSetForm(java.awt.Frame parent, boolean modal, Word[] wordArray, String title, boolean phoneticLanguage) {
        super(parent, modal);
        initComponents();
        this.phoneticLanguage = phoneticLanguage;
        numWords = wordArray.length;
        //enters the vocabulary set title and words in the set
        Title.setText(title);
        WordSet.setListData(wordArray);
        for (int i = 0; i < numWords; i++) {  
            this.wordArray[i] = wordArray[i];
        }
    }

    //Constructor form for adding a new vocabulary set
    public EditSetForm(java.awt.Frame parent, boolean modal, boolean phoneticLanguage) {
        super(parent, modal);
        initComponents();
        this.phoneticLanguage = phoneticLanguage;
    }

    
    public Word[] getWordSet() {
        Word[] finalWordArray = new Word[numWords];
        for (int i = 0; i < numWords; i++) {
            finalWordArray[i] = wordArray[i];
        }
        return finalWordArray;
    }

    public String getTitle() {
        return title;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WordSet = new javax.swing.JList();
        Edit = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(WordSet);

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Title");

        Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 329, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(Delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(Add, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Save, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(Cancel)
                            .add(Edit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Title)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {Add, Cancel, Delete, Edit, Save}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(Add)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Edit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Delete)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Save)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Cancel))
                    .add(jScrollPane1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {Add, Cancel, Delete, Edit, Save}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleActionPerformed

    //Allows the user to add words to the set by directing to the addWordform
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        //Opens the addword window
        AddWordForm aw = new AddWordForm(this, true, phoneticLanguage);
        aw.setVisible(true);
        
        //Increments the number of words and stores the word in the array
        //Mastery Factor: Arrays
        wordArray[numWords++] = aw.getWord();
        
        //Updates the list field
        //Mastery Factor: Additional Java Libraries
        WordSet.setListData(Arrays.copyOfRange(wordArray, 0, numWords));
    }//GEN-LAST:event_AddActionPerformed

    //Allows the user to edit words in the set
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        //Prevents editing without selecting the word
        if (WordSet.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "You must select a word to edit");
        } else {
            //Opens the edit word form
            AddWordForm aw;
            Word selectedWord = wordArray[WordSet.getSelectedIndex()];
            if (phoneticLanguage) {
                aw = new AddWordForm(this, true, (WordWPron) selectedWord, phoneticLanguage);
            } else {
                aw = new AddWordForm(this, true, (WordWOPron) selectedWord, phoneticLanguage);
            }
            aw.setVisible(true);
            //Updates
            wordArray[WordSet.getSelectedIndex()] = aw.getWord();
            WordSet.setListData(Arrays.copyOfRange(wordArray, 0, numWords));
        }
    }//GEN-LAST:event_EditActionPerformed

    //Saves the vocabulary set
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        //Stores the title of the vocabulary set
        title = Title.getText();
        if (title.equals("")) {
            //Prevents saving without a title
            JOptionPane.showMessageDialog(null, "Please indicate the title of the vocabulary set");
        } else if (title.length() > AppLogic.TITLE_RECORD_SIZE) {
            //Limits the number of characters that user can for the title
            JOptionPane.showMessageDialog(null, "Please limit the title of your vocabulary set to "
                    + AppLogic.TITLE_RECORD_SIZE + " characters");
        } else if (numWords == 0) {
            //Prevents saving if no words in the set
            JOptionPane.showMessageDialog(null, "You have not entered any words to the set");
        } else {
            title = Title.getText();
            //Closes the form
            this.dispose();
        }
    }//GEN-LAST:event_SaveActionPerformed

    //Closes the form
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    //Deletes the word in the set
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        //Prevents deletion without specifying which word
        if (WordSet.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "You must select a word to delete");
        } else {
            if (WordSet.getSelectedIndex() + 1 == numWords) {
                //Deletes the last member of the word array
                wordArray[WordSet.getSelectedIndex()] = null;
            } else {
                //Rearranges the array
                for (int i = WordSet.getSelectedIndex(); i < numWords - 1; i++) {
                    wordArray[i] = wordArray[i + 1];
                }
                //Deletes the last member
                wordArray[numWords - 1] = null;
            }
            //Decrements number of words
            numWords--;
        }
        //Updates the list field
        WordSet.setListData(Arrays.copyOfRange(wordArray, 0, numWords));
    }//GEN-LAST:event_DeleteActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Title;
    private javax.swing.JList WordSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
